### ISSUE TITLE
SMD #09 User Story I: Design Login Screen

### ISSUE THREAD

**Issue by ferrinsentermsu** [Intro-to-SE-Lab-Fall-21/Group03#9]
Design User Registration Screen using Flask

**Comment by MSpillers** [comment]
Changed name to make referencing commits and pull requests easier.

**Comment by MSpillers** [comment]
+Design Login Screen with Bootstrap and CSS Styles
+Implemented Login Functionality using SQLALCHEMY and Flask Forms
